'use strict';
const visual=document.querySelector('#visual'), title=document.querySelector('#title'), message=document.querySelector('#message'), eyebrow=document.querySelector('#eyebrow'), action=document.querySelector('#action'), note=document.querySelector('#note');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
let stage='intro', timers=[], journeyAnimation;
const mapData=fetch('assets/land.json').then(r=>{if(!r.ok)throw new Error('Map unavailable');return r.json()}).catch(()=>null);
const text={intro:['A LITTLE SOMETHING, JUST FOR YOU','Need a hug,<br><em>Prelize?</em>','I wish I could be there to give you one.<br>Until then, I made you this.','Get a hug from me ♡','No expiry date. Come back whenever you need me.'],travel:['SENT WITH A WHOLE LOT OF CARE','One hug,<br><em>on its way.</em>','From my corner of the world,<br>all the way to yours.','Travelling…','Some things are worth crossing the world for.'],arrived:['SPECIAL DELIVERY: YOU','Your hug<br><em>has arrived.</em>','A little piece of Portland,<br>with your name on it.','Receive my hug ♡','Take a breath. This one’s just for you.'],hug:['E-HUG SUCCESSFULLY DELIVERED','Come here.<br><em>I’ve got you.</em>','Stay here a little.<br>There’s no rush.','Stay in this hug ♡','Just imagine me holding you a little tighter.'],surprise:['WAIT… ONE MORE THING','There’s a surprise<br><em>in this hug.</em>','I couldn’t send you a hug<br>without bringing you flowers.','Open your surprise','Something pretty for my pretty girl.'],bouquet:['PINK TULIPS & WHITE LILIES','For you,<br><em>always.</em>','For the times I’m a little too far away<br>to give you the real thing.<br><br>Miss you.<br>— Nikhar ♡','Hug me again ♡','Save this link. My hugs are here whenever you want one.']};
function clearTimers(){timers.forEach(clearTimeout);timers=[];if(journeyAnimation)journeyAnimation.cancel();journeyAnimation=null}
function later(fn,ms){timers.push(setTimeout(fn,ms))}
function setCopy(s){const t=text[s];eyebrow.textContent=t[0];title.innerHTML=t[1];message.innerHTML=t[2];action.textContent=t[3];note.textContent=t[4];document.querySelector('.copy').getAnimations().forEach(a=>a.cancel());if(!reduced.matches)document.querySelector('.copy').animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:500});document.querySelectorAll('.progress span').forEach((e,i)=>e.classList.toggle('active',i===(s==='intro'?0:['travel','arrived'].includes(s)?1:2)))}
function particles(){if(reduced.matches)return;for(let i=0;i<18;i++){const h=document.createElement('span');h.className='heart';h.textContent=i%3?'♡':'♥';h.style.setProperty('--x',`${Math.random()*96}%`);h.style.setProperty('--size',`${14+Math.random()*20}px`);h.style.setProperty('--duration',`${3+Math.random()*3}s`);h.style.animationDelay=`${Math.random()*1.5}s`;document.querySelector('#hearts').append(h);h.addEventListener('animationend',()=>h.remove(),{once:true})}}
function characters(pose=''){visual.innerHTML=`<div class="characters ${pose}" role="img" aria-label="Illustrated Nikhar and Prelize ${pose?'sharing a warm hug':'standing together'}"></div>`}
function projection([lon,lat]){return [(lon+180)*500/360,(85-lat)*260/170]}
function landPath(data){if(!data)return '';return data.features.map(f=>{const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];return polys.map(p=>p.map(r=>r.map((coord,i)=>{const [x,y]=projection(coord);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join('')+'Z').join('')).join('')}).join('')}
async function travel(){stage='travel';clearTimers();setCopy(stage);action.disabled=true;visual.innerHTML='<div class="map-wrap"><p class="map-caption">Packing your hug…</p></div>';const data=await mapData;if(stage!=='travel')return;const [px,py]=projection([-122.6765,45.5231]),[jx,jy]=projection([28.0473,-26.2041]);const d=`M${px},${py} Q245,-10 ${jx},${jy}`;visual.innerHTML=`<div class="map-wrap"><svg viewBox="0 0 500 275" role="img" aria-label="A hug travelling from Portland Oregon to Johannesburg South Africa"><path class="land" d="${landPath(data)}"/><path class="route" id="flight" d="${d}"/><circle class="map-dot" cx="${px}" cy="${py}" r="5"/><circle class="map-dot" cx="${jx}" cy="${jy}" r="5"/><text class="map-label" x="${px-20}" y="${py+25}">Portland</text><text class="map-label" x="${jx-36}" y="${jy+27}">Johannesburg</text><g id="traveler"><text class="traveler" x="-10" y="7">♥</text></g></svg><div class="map-caption">Across the world. Straight to you.</div></div>`;const path=document.querySelector('#flight'),heart=document.querySelector('#traveler'),length=path.getTotalLength();const duration=reduced.matches?600:5200;const start=performance.now();function tick(now){if(stage!=='travel')return;const progress=Math.min((now-start)/duration,1),p=path.getPointAtLength(progress*length);heart.setAttribute('transform',`translate(${p.x} ${p.y})`);if(progress<1)requestAnimationFrame(tick);else{stage='arrived';setCopy(stage);action.disabled=false;action.focus({preventScroll:true});particles()}}requestAnimationFrame(tick)}
function receive(){stage='hug';clearTimers();setCopy(stage);characters('hug');particles();action.disabled=true;later(()=>{if(stage==='hug'){stage='surprise';setCopy(stage);action.disabled=false;action.focus({preventScroll:true});visual.innerHTML='<div class="surprise-symbol" role="img" aria-label="A surprise waiting to be opened">♡</div>'}},4200)}
action.addEventListener('click',()=>{if(stage==='intro')travel();else if(stage==='arrived')receive();else if(stage==='surprise'){stage='bouquet';clearTimers();setCopy(stage);visual.innerHTML='<img class="bouquet" src="assets/bouquet.webp" alt="A bouquet of pink tulips and white lilies wrapped in pink paper with a satin bow">';particles()}else if(stage==='bouquet'){document.querySelector('#hearts').replaceChildren();stage='intro';clearTimers();setCopy(stage);characters();action.disabled=false;travel()}});
window.addEventListener('pagehide',clearTimers);
